# Generated by Django 6.0.6 on 2026-06-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conversation_message_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='reject_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='request',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
