# Generated by Django 6.0.6 on 2026-06-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='request',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
